-- Migration number: 0002 	 autogenerated
CREATE TABLE IF NOT EXISTS job_functions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  active INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- Helpful index for lookups by slug
CREATE INDEX IF NOT EXISTS idx_job_functions_slug ON job_functions(slug);

-- Trigger to keep updated_at current (D1 supports sqlite triggers)
CREATE TRIGGER IF NOT EXISTS trg_job_functions_updated_at
AFTER UPDATE ON job_functions
FOR EACH ROW
BEGIN
  UPDATE job_functions SET updated_at = datetime('now') WHERE id = NEW.id;
END;
